### ISSUE TITLE
[Feature Request]: Add badges to control buttons (uosc)

### ISSUE THREAD

**Issue by NaiveInvestigator** [christoph-heinrich/mpv-quality-menu#11]
If we could add badges similar to how it works on the inbuilt subtitle, audio, video button, would be awesome!
![image](https://user-images.githubusercontent.com/72654596/193098009-49cfd5c5-ccdd-4860-9b00-9b712901c455.png)

Edit: Sorry if this was already implemented, I couldn't figure out how to do so sadly after much experimentation.

**Comment by christoph-heinrich** [comment]
I don't think that is currently possible. Maybe ask over on uosc if adding such functionality is an option.

**Comment by tomasklaen** [comment]
Make the script set the value of `foo` to `1`.

```lua
mp.commandv('script-message-to', 'uosc', 'set', 'foo', 1)
```

This property can now be used as a control button badge by prefixing it with `@`.

```
controls=command:icon_name:command_name#@foo?My foo button
```
