### ISSUE TITLE
[Feature Request]: Add menu for subtitles

### ISSUE THREAD

**Issue by NaiveInvestigator** [christoph-heinrich/mpv-quality-menu#13]
I think it might be useful in certain cases where comments of vids are saved in another language or if we watch vids that are not usually in the language we watch. 

An example of this would be this: https://youtu.be/5Mh3o886qpg?t=975

**Comment by christoph-heinrich** [comment]
What's the point in that? Subtitles already work fine as they are.
You're using uosc right? In the video you posted the subtitle menu looks like this for me.
![image](https://user-images.githubusercontent.com/8932183/197397034-0b73097d-f3d6-4406-b63d-8e724ff6bb97.png)
To only list languages that are useful to you, you can add e.g. `ytdl-raw-options=sub-langs=[en,de]` to your mpv.conf

**Comment by NaiveInvestigator** [comment]
>You're using uosc right? In the video you posted the subtitle menu looks like this for me.

yep this looks perfect!

But I think you misunderstood me, change the language to English (Canada), out there the uploader posted his comments and extra details about the vid on that subtitle language track, that was what I was trying to say. Sometimes users might need to change the language for that reason. Or sometimes uploaders might upload their custom subs for their vids not on `en` lang but at `en-US` or etc. ofc i can add that in `mpv.conf` but I can't predict each and every language they might add the subs in.

and if ppl don't need it they can just choose not enable that keybinding ig

**Comment by christoph-heinrich** [comment]
> Or sometimes uploaders might upload their custom subs for their vids not on `en` lang but at `en-US` or etc. ofc i can add that in `mpv.conf` but I can't predict each and every language they might add the subs in

`sub-langs` does support regex, so you could use something like `[en.*,de.*]` :wink:
