### ISSUE TITLE
If failed to fetch the available format then this script will crash due to the `err` is nil

### ISSUE THREAD

**Issue by dyphire** [christoph-heinrich/mpv-quality-menu#15]
![image](https://user-images.githubusercontent.com/61936050/198554468-6d525d4b-1e83-41fc-ae01-15c6b1b6781b.png)
The reason appears on this code:
https://github.com/christoph-heinrich/mpv-quality-menu/blob/a9168280eb94c753fa9c5f2d6ac38b931e201fae/quality-menu.lua#L383-L387

Please refer to the processing approach of the related code in [ytdl_hook.lua](https://github.com/mpv-player/mpv/blob/adb556bf15e9b09afce6c9cb0a0911c53cf27feb/player/lua/ytdl_hook.lua#L845-L877).

Maybe we can just apply the following changes:
```lua
if (json == nil) then
    if err == nil then err = "unexpected error occurred" end
    mp.osd_message("fetching formats failed...", 2)
    msg.error("failed to parse JSON data: " .. err)
    return
end
```

**Comment by christoph-heinrich** [comment]
Good catch. I've copied over the code from ytdl_hook.lua for error handling and also your suggestion in a62fe558db0d56db524ef9d3da2ab13eb335a124.

I'll make a new release if neither of us notice any problems with it in the next few days.

**Comment by dyphire** [comment]
Now it looks good. Close.
