### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by christoph-heinrich** [christoph-heinrich/mpv-quality-menu#16]
So far there is no license, which has bothered me ever since I made the fork.
I would like to add a GPL-2 license, because that's what mpv uses and it does use some code from there.
Is this fine with all of you?

@jgreco
@dyphire
@Natural-Harmonia-Gropius
@Francicoria
@DeadSix27

**Comment by Francicoria** [comment]
Good for me

**Comment by christoph-heinrich** [comment]
It's been over a week and the only person missing is @jgreco.
Considering their lack of activity over the past two years both here on GitHub over on GitLab, I don't expect that to change anytime soon (or ever). Since they made their project openly available, I think it's reasonable to assume that they wouldn't have a problem with adding that license.
I'll remove the license again if they ever show up and have a problem with it.
