### ISSUE TITLE
absence of scaling of the script text

### ISSUE THREAD

**Issue by AdventurerRussia** [christoph-heinrich/mpv-quality-menu#17]
when changing the window size, the text size remains the same, that is, if the player is in a small window, then the text goes off the screen, using the example of the webm script, everything is fine with these and there is the correct logic for mastabbing the text

here's the video https://youtu.be/5brsCnfu5tM

**Comment by christoph-heinrich** [comment]
There is an option `scale_playlist_by_window` that does exactly that.

**Comment by AdventurerRussia** [comment]
> 

okay, it's my own fault that I didn't figure it out, but it's very strange that it's not enabled by default
