### ISSUE TITLE
Quality selection is not working when `ytdl-format` is set in mpv.conf

### ISSUE THREAD

**Issue by ma-zsola** [christoph-heinrich/mpv-quality-menu#19]
When I set `ytdl-format` parameter in my mpv.conf the fetching is succesful, but the quality selecton does not take effect. 
The quality remains at the value set in the `ytdl-format` parameter.
I need to use `ytdl-format` setting, because my hardware cannot handle 8K videos.
Can you helo me with this?

**Comment by christoph-heinrich** [comment]
I'm using `ytdl-format` in my mpv.conf too, but quality selection works perfectly fine for me.
Do you see an error in the log file or something?
You can also try querying ytdl-format after you've selected it via the script to check that it has actually been set. You can do that with `print-text ${ytdl-format}` in the console.

**Comment by ma-zsola** [comment]
These are my relevant settings in mpv.conf:
```
[protocol.https]
--save-position-on-quit=no
--ytdl-format="bestvideo[height<=?2160]+bestaudio/best"
--ytdl-raw-options-append=no-cache-dir=
--ytdl-raw-options-append=write-subs=
```
This is the console content when I'm trying to switch to 1080p quality (sample url: https://www.youtube.com/watch?v=-ucUFBTUYLI):
![kép](https://user-images.githubusercontent.com/106858326/209548824-bba34e61-c54b-4515-a4c6-29fe76263bfa.png)

Nevertheless, the quality menu shows the correct selection:
![kép](https://user-images.githubusercontent.com/106858326/209549581-eb77928e-0b89-48cc-b500-28d5b45a8903.png)
 
Without ytdl-format setting, everything works fine. I don't really know what's wrong with my ytdl setting.

**Comment by christoph-heinrich** [comment]
So, I've tried reproducing it now and I know what's going on here.

You set `ytdl-format` in a conditional profile, and so when this script sets `ytdl-format` and reloads the video, the conditional profile gets applied again and it overwrites the changes from this script.

If you put those options in the mpv.conf without a profile, it will work.

**Comment by ma-zsola** [comment]
Thank you very much for the help. Without the profile, it works now. :-)
