### ISSUE TITLE
provide an option to fetch when key-binding is pressed

### ISSUE THREAD

**Issue by Y0J1G3N** [christoph-heinrich/mpv-quality-menu#2]
jgreco's mpv-youtube-quality  only start fetching when pressed CTRL+F,but mpv-quality-menu will start fetching when pasted the url.Sometimes it is not necessary to change the format,would like to provide an option to fetch when key-binding is pressed?

**Comment by christoph-heinrich** [comment]
I just pushed for1d42c553b2684fbdca822c05e8364c67444d53e5 to master, is that good?

**Comment by Y0J1G3N** [comment]
> I just pushed [1d42c55](https://github.com/christoph-heinrich/mpv-quality-menu/commit/1d42c553b2684fbdca822c05e8364c67444d53e5) to master, is that good?

I just read and understood the code an hour before and found a way to modify it. I was about to submit a pull request, but I didn't expect you to have solved it. What a coincidence, just like I thought.
