### ISSUE TITLE
how to use osc.patch in mpv.net?

### ISSUE THREAD

**Issue by candrapersada** [christoph-heinrich/mpv-quality-menu#20]

**Comment by christoph-heinrich** [comment]
I have never used mpv.net, so I can't say for sure, but based on screenshots it looks like it uses the regular osc, and so using the patched osc instead should just work... in theory.
Try saving the [already patched osc](https://github.com/christoph-heinrich/mpv-quality-menu/blob/master/quality-menu-osc.lua) in your scripts directory and put `osc=no` in your mpv.conf (or whatever the mpv.net equivalent would be) as is described in point 4 of the [installation instructions](https://github.com/christoph-heinrich/mpv-quality-menu#installation).

**Comment by candrapersada** [comment]
what I mean is [osc.patch](https://github.com/christoph-heinrich/mpv-quality-menu/blob/master/osc.patch) not osc.lua

**Comment by christoph-heinrich** [comment]
That patch is for _patching_ `osc.lua`, which results in `quality-menu-osc.lua`.
mpv.net seems to use `osc.lua`, and so using the osc extension should work just like it would for the regular mpv.
