### ISSUE TITLE
uosc badges only displayed after changing audio/video quality or reloading stream

### ISSUE THREAD

**Issue by xfzv** [christoph-heinrich/mpv-quality-menu#21]
I have the following in `uosc.conf`:

```
controls=menu,gap,<has_many_audio>audio,<!has_many_audio,has_audio,stream>command:graphic_eq:script-binding quality_menu/audio_formats_toggle#@aformats>1?Audio,<has_chapter>chapters,<has_sub>subtitles,<!has_many_video,video,stream>command:theaters:script-binding quality_menu/video_formats_toggle#@vformats>1?Video
```

- When opening a stream, this is what the uosc controls bar looks like:
![image](https://user-images.githubusercontent.com/78810647/211535522-98697d86-3be9-4684-be34-f6446843fe5c.png)

- After choosing another video quality (not sure why the audio icon disappeared):
![image](https://user-images.githubusercontent.com/78810647/211535728-4d9eb463-fec1-444f-99fb-53c5a6029643.png)

- After either choosing another audio quality or reloading the stream with `script-binding quality_menu/reload`:
![image](https://user-images.githubusercontent.com/78810647/211535895-082420ea-f69d-4f43-a44b-d9b696f2736e.png)

Is this a limitation or is there a way to get the badges for audio and video right when the stream starts?

I'm using yt-dlp 2023.01.06 if that matters.

**Comment by christoph-heinrich** [comment]
I've never encountered that and your `controls` config works just fine for me when I tested it with YouTube videos.
Does that always happen for you or only with specific videos?
