### ISSUE TITLE
Is there a way to set the default quality to not be the highest

### ISSUE THREAD

**Issue by Sininenblue** [christoph-heinrich/mpv-quality-menu#22]
I'd like to be able to set specific resolutions to be what automatically gets picked if I run `mpv [link]`

**Comment by christoph-heinrich** [comment]
You can configure that with [`ytdl-format`](https://mpv.io/manual/master/#options-ytdl-format) in your `mpv.conf`.

**Comment by Sininenblue** [comment]
Didn't know that existed, thanks!
