### ISSUE TITLE
Audio/Video "open menu" in uosc is now inverted

### ISSUE THREAD

**Issue by xfzv** [christoph-heinrich/mpv-quality-menu#25]
Before updating to https://github.com/christoph-heinrich/mpv-quality-menu/commit/c413444544aab63713c7fe10bb12822f2d12030c:

![image](https://user-images.githubusercontent.com/78810647/217924442-09c25ac9-00d1-4870-9f3f-17b126c7f87d.png)

![image](https://user-images.githubusercontent.com/78810647/217924448-a59954b0-3665-4c56-ae24-d90491ec7398.png)

---

After updating to https://github.com/christoph-heinrich/mpv-quality-menu/commit/c413444544aab63713c7fe10bb12822f2d12030c:

![image](https://user-images.githubusercontent.com/78810647/217924394-175944e2-b858-411f-b631-28cde0ab6fd3.png)
![image](https://user-images.githubusercontent.com/78810647/217924407-def16a41-4b8a-4747-af3f-e4684ca6d612.png)

**Comment by christoph-heinrich** [comment]
How did I not notice that :laughing:
Thanks
