### ISSUE TITLE
Script crashes

### ISSUE THREAD

**Issue by ma-zsola** [christoph-heinrich/mpv-quality-menu#26]
I use the script without uosc.
I tested it with a freshly downloaded lua, without any changes.

Error message:
quality-menu.lua: 152: bad argument # 1 to 'ipairs' (table expected, got nil)

**Comment by natural-harmonia-gropius** [comment]
With uosc also crashing. I'm using pre-release v4.

![image](https://user-images.githubusercontent.com/50797982/218061024-b22b67e4-cc02-402e-852d-6a12cb21f2af.png)
