### ISSUE TITLE
[Feature Request]: Download video/audio from youtube via yt-dlp

### ISSUE THREAD

**Issue by NaiveInvestigator** [christoph-heinrich/mpv-quality-menu#27]
Something simliar to this
https://github.com/dyphire/mpv-config/blob/master/scripts/youtube-download.lua

I think it would a nice option of have.

**Comment by christoph-heinrich** [comment]
What would be the benefit of integrating that functionality here instead of using that script?
I've never used it but at a quick glance it looks like that gets the format from `ytdl-format`, so it should be possible to set whatever quality you want to download in quality-menu and then download that using youtube-download.

**Comment by NaiveInvestigator** [comment]
> so it should be possible to set whatever quality you want to download in quality-menu and then download that using youtube-download.

Ah would be nice if that was possible, I just mainly wanted the script to use uosc's menus. But i don't know how to implement that, How should I go to add that functionality?

**Comment by christoph-heinrich** [comment]
I'd try something like this
```
ctrl+d script-binding youtube_download/download-video #! Download > Video
ctrl+a script-binding youtube_download/download-audio #! Download > Audio
```
the keys have to match those in the config for youtube-download. Unfortunately they expose the bindings only when they are set in their config.

Afaik dyphire is a uosc user, so you can certainly ask him how to best integrate it :wink:

**Comment by omaru-ok** [comment]
i also did somehting similar 
```
Ctrl+e run wt.exe yt-dlp  	"${path}" --embed-metadata --embed-chapter --sub-langs en-orig,en -o %USERPROFILE%\.cache\mpv\%(title)s.%(ext)s ; show_text ":O Downloading ${filename}" # Download currently playing video to  using yt-dlp
``` 
inside my `input.conf`
