### ISSUE TITLE
stock osc and uosc overlapping issue [issue seems to be present only using quality-menu script]

### ISSUE THREAD

**Issue by bachig26** [christoph-heinrich/mpv-quality-menu#28]
https://github.com/tomasklaen/uosc/discussions/463

I have attached my config [scripts and others] in a zip file in this above discussion, please have a look and help me with the stock osc and uosc overlapping.

I'm only having this overlapping issue only when I rtry with [mpv-quality-menu](https://github.com/christoph-heinrich/mpv-quality-menu).

**Comment by christoph-heinrich** [comment]
The problem is that you use the `quality-menu-osc.lua` together with uosc. That's why the installation instructions state to **pick one**, not both :wink:

**Comment by bachig26** [comment]
> The problem is that you use the `quality-menu-osc.lua` together with uosc. That's why the installation instructions state to **pick one**, not both 😉

yes, thanks... I didn't notice it completely.
