### ISSUE TITLE
select quality single

### ISSUE THREAD

**Issue by candrapersada** [christoph-heinrich/mpv-quality-menu#29]
is there any option to select video quality without audio separately like `best[height<=360]`, `best[height<=720]` for youtube

**Comment by christoph-heinrich** [comment]
That is a use case I didn't consider, but I think it should work if you specify the formats in `quality_strings_video` with `best[...]` and `quality_strings_audio=[]`.

**Comment by christoph-heinrich** [comment]
Since you've been sleeping on this, I've now tested it myself and the suggested solution works.
