### ISSUE TITLE
Videos on some websites will display a lot of useless information

### ISSUE THREAD

**Issue by dyphire** [christoph-heinrich/mpv-quality-menu#3]
use mpv to open https://www.bilibili.com/video/BV1234y1H7pV, then open the video menu. There will display a lot of useless information.

screenshot
![image](https://user-images.githubusercontent.com/61936050/179216844-f4d57dff-4d14-40a1-b8cc-b40358a70efd.png)

I think we can do extra processing on the obtained video format to exclude useless data that without effective resolution.

**Comment by christoph-heinrich** [comment]
I'm having a real hard time reproducing that. I'm using the lastest master of yt-dlp and youtube-dl.
Can you send me the output of `yt-dlp -J --no-warnings --flat-playlist 'https://www.bilibili.com/video/BV1234y1H7pV?p=1'` please?

**Comment by dyphire** [comment]
> I'm having a real hard time reproducing that. I'm using the lastest master of yt-dlp and youtube-dl. Can you send me the output of `yt-dlp -J --no-warnings --flat-playlist 'https://www.bilibili.com/video/BV1234y1H7pV?p=1'` please?

I'm also using the lastest master of yt-dlp.
[ytdlp-log.txt](https://github.com/christoph-heinrich/mpv-quality-menu/files/9121421/ytdlp-log.txt)

**Comment by christoph-heinrich** [comment]
And i think this patch should solve it in your case, but I'm not sure making it solely dependent on resolution is ideal.
``` patch
diff --git a/quality-menu.lua b/quality-menu.lua
index eb4f45c..3c10879 100644
--- a/quality-menu.lua
+++ b/quality-menu.lua
@@ -321,7 +321,7 @@ local function download_formats()
             size = scale_filesize(format.filesize)
         end
         return {
-            resolution = format.resolution or string.format("%sx%s", format.width, format.height),
+            resolution = format.resolution or "",
             fps = format.fps and format.fps.."fps" or "",
             dynamic_range = format.dynamic_range or "",
             bitrate_total = scale_bitrate(format.tbr),
@@ -338,11 +338,15 @@ local function download_formats()
     end
 
     for i,f in ipairs(video_formats) do
-        video_formats[i].labels = format_label(f.format)
+        if f.format.resolution then
+            video_formats[i].labels = format_label(f.format)
+        end
     end
 
     for i,f in ipairs(audio_formats) do
-        audio_formats[i].labels = format_label(f.format)
+        if f.format.resolution then
+            audio_formats[i].labels = format_label(f.format)
+        end
     end
 
     local function format_table(formats, columns)
```

**Comment by dyphire** [comment]
No, this patch will not render menus on this video.

**Comment by dyphire** [comment]
After some research, I found that `m4s` format files are actually cache files. The script parses these cache data and displays them on the video menu.

**Comment by christoph-heinrich** [comment]
Sorry I missed your post with the output of yt-dlp. This should fix it for you, but I don't like that solution. I'll figure out something better for master.
```
diff --git a/quality-menu.lua b/quality-menu.lua
index eb4f45c..e777e9d 100644
--- a/quality-menu.lua
+++ b/quality-menu.lua
@@ -232,7 +232,9 @@ local function download_formats()
         local is_video = (format.vcodec and format.vcodec ~= "none") or (format.video_ext and format.video_ext ~= "none")
         local is_audio = (format.acodec and format.acodec ~= "none") or (format.audio_ext and format.audio_ext ~= "none")
         if is_video then
-            video_formats[#video_formats+1] = {format=format}
+            if format.resolution then
+                video_formats[#video_formats+1] = {format=format}
+            end
         elseif is_audio and not is_video then
             audio_formats[#audio_formats+1] = {format=format}
         end
@@ -321,7 +323,7 @@ local function download_formats()
             size = scale_filesize(format.filesize)
         end
         return {
-            resolution = format.resolution or string.format("%sx%s", format.width, format.height),
+            resolution = format.resolution,
             fps = format.fps and format.fps.."fps" or "",
             dynamic_range = format.dynamic_range or "",
             bitrate_total = scale_bitrate(format.tbr),
```

**Comment by christoph-heinrich** [comment]
I've changed the video and audio detection on the [dev](https://github.com/christoph-heinrich/mpv-quality-menu/tree/dev) branch. Would be great if you can test some sites with it to see if it works for you.
Seems reliable based on everything I have tested so far.

**Comment by dyphire** [comment]
> I've changed the video and audio detection on the [dev](https://github.com/christoph-heinrich/mpv-quality-menu/tree/dev) branch. Would be great if you can test some sites with it to see if it works for you. Seems reliable based on everything I have tested so far.

Yes, the script of dev branch fix the issue for me.

**Comment by pukkandan** [comment]
> > I'm having a real hard time reproducing that. I'm using the lastest master of yt-dlp and youtube-dl. Can you send me the output of `yt-dlp -J --no-warnings --flat-playlist 'https://www.bilibili.com/video/BV1234y1H7pV?p=1'` please?
> 
> I'm using the lastest release of yt-dlp. [ytdlp-log.txt](https://github.com/christoph-heinrich/mpv-quality-menu/files/9121421/ytdlp-log.txt)

I can't reproduce this json output. @dyphire Could you open an issue on [yt-dlp](https://github.com/yt-dlp/yt-dlp/issues/new/choose) with the relevant verbose log?

**Comment by dyphire** [comment]
> I can't reproduce this json output. Could you open an issue on [yt-dlp](https://github.com/yt-dlp/yt-dlp/issues/new/choose) with the relevant verbose log?

I don't know what issue I need to open.

**Comment by pukkandan** [comment]
You can use the "broken site" template. Just make sure to update yt-dlp and to give full verbose log

**Comment by christoph-heinrich** [comment]
Btw I "broke" this again in the latest release, and instead rely on [this](https://github.com/yt-dlp/yt-dlp/issues/4373#issuecomment-1186637357) for deciding if its a video or audio format. If you want this fixed properly, report it over there.

**Comment by dyphire** [comment]
> Btw I "broke" this again in the latest release, and instead rely on [this](https://github.com/yt-dlp/yt-dlp/issues/4373#issuecomment-1186637357) for deciding if its a video or audio format. If you want this fixed properly, report it [here](https://github.com/yt-dlp/yt-dlp/issues/new?assignees=&labels=triage%2Csite-bug&template=1_broken_site.yml).

Thanks for reminding me. I forgot it accidentally.
In addition, I think the correct change should be this:
```lua
local is_video = format.vcodec and format.vcodec ~= "none"
local is_audio = format.acodec and format.acodec ~= "none"
```

**Comment by christoph-heinrich** [comment]
When it's null, it could still be a video/audio.
This certainly leads to less false positives, but it will also lead to some false negatives.
Not sure which way i should go...
I could also create a new option, so people can choose themselves if they want to have null codecs in their list or not.

**Comment by dyphire** [comment]
> When it's null, it could still be a video/audio. This certainly leads to less false positives, but it will also lead to some false negatives. Not sure which way i should go... 

I think we should ensure that it is video/audio, and this change can also avoid wrong formats like 'm4s', fix this isue.
In addition, can you give a specific example of video or audio when codec is nil?

At the same time, this is also the code logic in [ytdl_hook.lua](https://github.com/mpv-player/mpv/blob/master/player/lua/ytdl_hook.lua) of the mpv official script. 
 https://github.com/mpv-player/mpv/blob/ad5a1ac8733e6b4cf86e7b6d84c50ddf37ca62cd/player/lua/ytdl_hook.lua#L421
It is necessary to follow it first, so I don't agree with the changes in your relevant PR on https://github.com/mpv-player/mpv/pull/10428, which will introduce wrong video/audio content.


> I could also create a new option, so people can choose themselves if they want to have null codecs in their list or not.

This is also an acceptable option, but the null codecs should be disabled by default.

**Comment by pukkandan** [comment]
PS: The logic in ytdl_hook seem to be faulty too
