### ISSUE TITLE
Quality-menu doesn't make use of --cookies-from-browser

### ISSUE THREAD

**Issue by GunGunGun** [christoph-heinrich/mpv-quality-menu#31]
For Bilibili.tv, the only way to get 1080p even higher is to pass cookies from web browser (with an account logging in) to MPV, it works with MPV and I got 1080p+:

![image](https://github.com/christoph-heinrich/mpv-quality-menu/assets/6913739/641a191d-5eb4-4414-87f1-44bc8ab3aeff)

But somehow, quality-menu doesn't show 1080p+:

![image](https://github.com/christoph-heinrich/mpv-quality-menu/assets/6913739/103725cc-694d-4867-9d9e-b1e9b55852cf)

Is threre a way to force quality-menu to use `--cookies-from-browser` for consistency ?

**Comment by christoph-heinrich** [comment]
How are you passing that option? `--ytdl-raw-options=cookies-from-browser=` should definitely work.
You can check how ytdl gets called in the verbose log (e.g. `--log-file=log.txt`), there should be a line `calling ytdl with command: ...`.

It's possible that the formats are not shown because it's not clear if those formats are video or audio formats.
To make sure they aren't hidden, try the option `include_unknown=yes`.

**Comment by GunGunGun** [comment]
> How are you passing that option? `--ytdl-raw-options=cookies-from-browser=` should definitely work. You can check how ytdl gets called in the verbose log (e.g. `--log-file=log.txt`), there should be a line `calling ytdl with command: ...`.
> 
> It's possible that the formats are not shown because it's not clear if those formats are video or audio formats. To make sure they aren't hidden, try the option `include_unknown=yes`.

I use this cmd `mpv https://www.bilibili.com/video/BV1ot411y7Q3/ --ytdl-raw-options-append=cookies-from-browser=firefox:D:\PB\Data\profilet`

And I do have `include_unknown=yes`

The result is still the same with `mpv https://www.bilibili.com/video/BV1ot411y7Q3/ --ytdl-raw-options-append=cookies-from-browser=firefox:D:\PB\Data\profilet --log-file=qualitymenu.txt`

Attached my log file:
![image](htt
[qualitymenu.txt](https://github.com/christoph-heinrich/mpv-quality-menu/files/12060018/qualitymenu.txt)
ps://github.com/christoph-heinrich/mpv-quality-menu/assets/6913739/6a922600-2cda-4bf6-8e72-f68e65609827)

So it doesn't work somehow.

**Comment by christoph-heinrich** [comment]
You're using an outdated version of quality-menu, [the last release](https://github.com/christoph-heinrich/mpv-quality-menu/releases/tag/v4.1.0) gained the feature to pass `ytdl-raw-options` to ytdl.

**Comment by GunGunGun** [comment]
> You're using an outdated version of quality-menu, [the last release](https://github.com/christoph-heinrich/mpv-quality-menu/releases/tag/v4.1.0) gained the feature to pass `ytdl-raw-options` to ytdl.

Ah, my bad, yeah I just checked my version is outdated: -- quality-menu 3.1.1 - 2023-Feb-04

This "not issue" is now solved, thanks!
