### ISSUE TITLE
how to use thumbfast and quality menu in osc without uosc?

### ISSUE THREAD

**Issue by candrapersada** [christoph-heinrich/mpv-quality-menu#33]
how to use thumbfast in [osc.lua](https://github.com/po5/thumbfast/blob/vanilla-osc/player/lua/osc.lua) (use this fork for vanilla UI) and quality menu in [osc](https://github.com/christoph-heinrich/mpv-quality-menu?tab=readme-ov-file#osc-extension)?

**Comment by christoph-heinrich** [comment]
You'll have to apply the patch mentioned [in the readme](https://github.com/christoph-heinrich/mpv-quality-menu#osc-extension) yourself.
I've never tried applying that patch to the osc.lua from thumbfast, so I don't know if it will apply cleanly, but it's a fairly simple patch so fixing it shouldn't be hard (or manually copy the changes over).
