### ISSUE TITLE
.config/mpv/scripts/quality-menu.lua:1: unexpected symbol near '{'

### ISSUE THREAD

**Issue by gybfefe** [christoph-heinrich/mpv-quality-menu#37]
mpv -v:
[cplayer] mpv v0.37.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Jan 19 2024 09:09:45
[cplayer] libplacebo version: v6.338.2
[cplayer] FFmpeg version: n6.1.1
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       58.29.100
[cplayer]    libavcodec      60.31.102
[cplayer]    libavformat     60.16.100
[cplayer]    libswscale      7.5.100
[cplayer]    libavfilter     9.12.100
[cplayer]    libswresample   4.12.100
[cplayer]
[cplayer] Configuration: -Db_lto=true -Db_pie=true -Dpython.bytecompile=1 -Dlibmpv=true -Dcaca=disabled -Dcdda=enabled -Ddvbin=enabled -Ddvdnav=enabled -Dlibarchive=enabled -Dopenal=enabled -Dprefix=/usr -Dlibexecdir=lib -Dsbindir=bin -Dauto_features=auto -Dbuildtype=plain -Dwrap_mode=nodownload
[cplayer] List of enabled features: alsa av-channel-layout avif-muxer build-date cdda cplugins cuda-hwaccel cuda-interop dmabuf-interop-gl dmabuf-wayland drm dvbin dvdnav egl egl-drm egl-helpers egl-wayland egl-x11 ffmpeg ffnvcodec gbm gl glibc-thread-name glob glob-posix gpl iconv jack javascript jpeg jpegxl lavu-uuid lcms2 libarchive libass libavdevice libbluray libdl libm libplacebo librt linux-fstatfs luajit manpage-build memfd-create noexecstack openal pipewire posix posix-shm ppoll pulse rubberband rubberband-3 shaderc sixel threads uchardet vaapi vaapi-drm vaapi-wayland vaapi-x11 vapoursynth vdpau vector vk-khr-display vt.h vulkan vulkan-interop wayland wayland-protocols-1-27 wayland-protocols-1-31 wayland-protocols-1-32 x11 xv zimg zimg-st428 zlib
[cplayer] Reading config file /etc/mpv/encoding-profiles.conf
[ifo_dvdnav] Opening /etc/mpv/encoding-profiles.conf
[bdmv/bluray] Opening /etc/mpv/encoding-profiles.conf
[file] Opening /etc/mpv/encoding-profiles.conf
[cplayer] Applying profile 'default'...
[cplayer] Reading config file /home/fefe/.config/mpv/mpv.conf
[ifo_dvdnav] Opening /home/fefe/.config/mpv/mpv.conf
[bdmv/bluray] Opening /home/fefe/.config/mpv/mpv.conf
[file] Opening /home/fefe/.config/mpv/mpv.conf
[cplayer] Applying profile 'default'...
[cplayer] Setting option 'fs' = 'yes' (flags = 4)
[cplayer] Setting option 'hwdec' = 'auto' (flags = 4)
[cplayer] Setting option 'x11-bypass-compositor' = 'no' (flags = 4)
[cplayer] Setting option 'volume-max' = '250' (flags = 4)
[cplayer] Setting option 'save-position-on-quit' = '' (flags = 4)
[cplayer] Setting option 'v' = '' (flags = 8)
[ifo_dvdnav] Opening /home/fefe/.config/mpv/input.conf
[bdmv/bluray] Opening /home/fefe/.config/mpv/input.conf
[file] Opening /home/fefe/.config/mpv/input.conf
[input] Parsing input config file /home/fefe/.config/mpv/input.conf
[input] Input config file /home/fefe/.config/mpv/input.conf parsed: 2 binds
[cplayer] mpv v0.37.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Jan 19 2024 09:09:45
[cplayer] libplacebo version: v6.338.2
[cplayer] FFmpeg version: n6.1.1
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       58.29.100
[cplayer]    libavcodec      60.31.102
[cplayer]    libavformat     60.16.100
[cplayer]    libswscale      7.5.100
[cplayer]    libavfilter     9.12.100
[cplayer]    libswresample   4.12.100
[cplayer]
[cplayer] Usage:   mpv [options] [url|path/]filename
[cplayer]
[cplayer] Basic options:
[cplayer]  --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
[cplayer]  --no-audio        do not play sound
[cplayer]  --no-video        do not play video
[cplayer]  --fs              fullscreen playback
[cplayer]  --sub-file=<file> specify subtitle file to use
[cplayer]  --playlist=<file> specify playlist file
[cplayer]
[cplayer]  --list-options    list all mpv options
[cplayer]  --h=<string>      print options which contain the given string in their name
[cplayer]
[cplayer] Set property: user-data/osc/visibility="auto" -> 1
[cplayer] Set property: user-data/osc/margins={"b":0,"r":0,"t":0,"l":0} -> 1

**Comment by christoph-heinrich** [comment]
IDK what you're running, but there is no `{` in line 1.
Also that output you've posted doesn't contain anything regarding the script.

**Comment by gybfefe** [comment]
Sry, i wanted to delete before you read :) The result of save as link on github... 
Great solution for usability, by the way congrats to all of you, should be default on base mpv....
