### ISSUE TITLE
Q about audio selection

### ISSUE THREAD

**Issue by plissken1138** [christoph-heinrich/mpv-quality-menu#5]
Is audio selection supposed to switch to playing audio only? 

If I start playing Youtube video and select another audio stream from audio only menu it continues playing video with that stream.

win10edu x64

**Comment by christoph-heinrich** [comment]
Generally (at least from YouTube) there are two streams. One for video and one for audio. With this menu you can select the quality of each stream.
If you want audio only, you have to tell mpv that you don't want video. You can do that with e.g. with `--no-video`, by cycling video tracks to none (default keybinding is `_`) or by creating your own keybinding in `input.conf` with `<key> set video no` (alternatively `set vid 0` would also work).
It is also possible to start mpv with something like `--ytdl-format=bestaudio` to get audio only.

**Comment by plissken1138** [comment]
Thanks for the info.

I usually play YT videos with "play with..." add-on in Firefox and I'd like to keep it opening with video as default, but thought it would be nice to have an option to switch to audio only through quality menu. I'll tinker some more with your suggestions.

**Comment by christoph-heinrich** [comment]
I guess it would also be possible to insert a line in each menu to select nothing. Should be pretty straight forward, I'll look into it.
