### ISSUE TITLE
osc button are not shown in mpv.net

### ISSUE THREAD

**Issue by soredake** [christoph-heinrich/mpv-quality-menu#6]
I don't have any scripts that modify osc.

**Comment by christoph-heinrich** [comment]
I don't think I'm doing something that could be causing this. Are you sure this script is to blame?

**Comment by soredake** [comment]
By "osc button" i mean this button https://raw.githubusercontent.com/christoph-heinrich/mpv-quality-menu/master/quality-menu-preview-osc.jpg, this button should be show, but it's not

**Comment by christoph-heinrich** [comment]
Did you install the the osc correctly?
> (optional) Save the quality-menu-osc.lua into your [scripts directory](https://mpv.io/manual/stable/#script-location) and put osc=no in your [mpv.conf](https://mpv.io/manual/stable/#location-and-syntax)

**Comment by soredake** [comment]
I overlooked this, sorry!
